(part "CMF1_1111_12"
    (packageRef "CMF1111112")
    (interface
        (port "1" (symbPinId 1) (portName "N") (portType INOUT))
        (port "2" (symbPinId 2) (portName "L") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "SCHURTER")
    (property "Manufacturer_Part_Number" "CMF1.1111.12")
    (property "Mouser_Part_Number" "693-CMF1.1111.12")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Schurter/CMF1111112?qs=%2F0Eb3QIYuIbNncoXboECMA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "CAD-model shows appliance inlet with PCB-terminals only, with line switch marking 0/1, snap-in mounting on PCB and fixation with screw to the centre position from the top, with rear-side insulation cover.")
    (property "Datasheet_Link" "https://www.schurter.com/en/datasheet/typ_CMF1.pdf")
    (property "symbolName1" "CMF1_1111_12")
)
